export default new class {
    interactions = [
        {
            id: 0,
            name: 'home',
            positions: [
                {x: -148, y: -292, facing: 0, action: 0}, {x: -484, y: -436, facing: 2, action: 1}, {x: -484, y: -388, facing: 2, action: 1}, {x: -148, y: -292, facing: 0, action: 2}, {x: -148, y: -292, facing: 0, action: 3}, {x: -484, y: -244, facing: 0, action: 4}, {x: -484, y: -244, facing: 0, action: 5},
            ],
            actions: [
                {
                    id: 0,
                    name: 'mom1',
                    type: 'chat',
                    messages: ['Mom: Hi honey, where have you been?', 'I have been waiting for you all day...', 'Could you please check the news on the TV?', 'I thought I heard something worrisome...'],
                    instaLock: false,
                    skippable: false,
                    thisLocks: [],
                },
                {
                    id: 1,
                    name: 'tv1',
                    type: 'noise',
                    messages: ['Journalist 1: This is bad...', 'Volcor, are you still there?', '...', 'Seems like we have technical difficulties.'],
                    instaLock: true,
                    skippable: false,
                    thisLocks: ['mom1'],
                },
                {
                    id: 2,
                    name: 'mom2',
                    type: 'chat',
                    messages: ["Mom: Oh no, that's bad...", 'Honey, can you please get your dad?', 'He said he was at Cloverleaf Town investigating his case.', "He needs to come now. It's very serious.", "...", "Nothing, honey. Don't worry.", 'There is no time for questions. Hurry, please...'],
                    instaLock: true,
                    skippable: false,
                    thisLocks: ['door1'],
                },
                {
                    id: 3,
                    name: 'mom3',
                    type: 'chat',
                    messages: ['Mom: Go get dad, NOW! He is at Cloverleaf Town investigating his case.', 'There is no time for questions. Hurry, please...'],
                    instaLock: false,
                    skippable: true,
                    thisLocks: [],
                },
                {
                    id: 4,
                    name: 'door1',
                    type: 'chat',
                    messages: ['Mom: Hey, is that you? Come here...'],
                    instaLock: false,
                    skippable: false,
                    thisLocks: [],
                },
                {
                    id: 5,
                    name: 'door2',
                    type: 'cutScene',
                    cutscene: 0,
                    instaLock: true,
                    thisLocks: ['mom2', 'mom3'],
                },
            ]
        },
        {
            id: 1,
            name: 'Cloverleaf Town',
            positions: [
                {x: -290, y: -260, facing: 0, action: 0}, {x: -322, y: -308, facing: 0, action: 1}, {x: -514, y: -596, facing: 0, action: 2}, {x: -226, y: -532, facing: 0, action: 3}, {x: -226, y: -532, facing: 0, action: 4},
            ],
            actions: [
                {
                    id: 0,
                    name: 'dadshouse',
                    type: 'chat',
                    messages: ['DAD?', '...', 'DAD, PLEASE OPEN THE DOOR!'],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                },
                {
                    id: 1,
                    name: 'dadshousesign',
                    type: 'chat',
                    messages: ["Volcor family's house"],
                    instaLock: false,
                    skippable: true,
                    thisLocks: [],
                },
                {
                    id: 2,
                    name: 'house1',
                    type: 'chat',
                    messages: ["...", 'Who is there?', 'What are you doing outside, kid?', "Have you not seen the news?", 'You better go home and hide!', '...', 'Mr. Volcor?', 'He is your father?', 'Oh God...', 'GO HOME NOW! Do not go look for your dad. He is a danger to all of us!'],
                    instaLock: false,
                    skippable: true,
                    thisLocks: [],
                },
                {
                    id: 3,
                    name: 'house2',
                    type: 'chat',
                    messages: ['Hey what are you doing outside?', "You should come inside, quick."],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                },
                {
                    id: 4,
                    name: 'house3',
                    type: 'scene',
                    newScene: 2,
                    x: -400,
                    y: -400,
                    messages: [],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                },
            ]
        },
        {
            id: 2,
            name: 'Cloverleaf Town House 1',
            positions: [
                {x: undefined, y: undefined, facing: undefined, action: 0}, {x: undefined, y: undefined, facing: undefined, action: 1},
            ],
            actions: [
                {
                    id: 0,
                    name: 'Raton',
                    type: 'chat',
                    messages: ['My god, you look terrible!', 'What happened to you?', '...', 'WHAT?', 'I know, it has been all over the news!', "I am SO glad you made it out alive...", '...', "Where is your mom?", "...", "...", "I am so sorry...", "You were looking for your dad in Cloverleaf Town?", "Wait a sec...", "HE is YOUR DAD?!", "We need to stop him! He is going to burn our world to ashes!", "...", "I have an idea.", "Do you own animals?", "...", "Okay. In that case, I am going to teach you how to own an animal.", "...", "You don't know?", "Your dad has invented a virus to make all animals stronger and angry!", "He took over the national laboratory.", "We can stop him by using the animals against him.", "They can fight...", "Wanna see?", "I'll show you tomorrow. You can stay here tonight since it's too dangerous to go out.", "I'm sorry for the mess. Electricity has been out since the explosion in your town.", "You can sleep on the couch. I'll sleep on the floor."],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                },
                {
                    id: 1,
                    name: 'Raton2',
                    type: 'scene',
                    messages: [],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                    newScene: 3,
                },
            ]
        },
        {
            id: 3,
            name: 'Forest 1',
            positions: [
                {x: undefined, y: undefined, facing: undefined, action: 0}, {x: undefined, y: undefined, facing: undefined, action: 1},
            ],
            actions: [
                // {
                //     id: 0,
                //     name: 'Raton',
                //     type: 'chat',
                //     messages: ["What took you so long to get ready?", "I'm glad you've finally made it here.", "Now let me show you how to tame an animal out in the wild.", "Please log in or create an account."],
                //     instaLock: true,
                //     skippable: false,
                //     thisLocks: [],
                // },
                {
                    id: 1,
                    name: 'Raton2',
                    type: 'choice',
                    fightId: 0,
                    messages: [],
                    choices: [
                        { // TODO: remember which choice was the last one, so you can go back to that choice if you made the wrong choice.
                            id: 0,
                            question: "Do you want to create an account or log in?",
                            choices: ["Create an account", "Log in"],
                            inputType: 1, // Select options with keys and enter
                            nextChoice: [1, 4],
                            consequence: -1, // no consequence
                        },
                        {
                            id: 1,
                            question: "Fill in a username:",
                            choices: [],
                            inputType: 2, // Fill in and submit with enter
                            nextChoice: [2],
                            consequence: 0,
                            keepData: true,
                        },
                        {
                            id: 2,
                            question: "Fill in an email:",
                            choices: [],
                            inputType: 2,
                            nextChoice: [3],
                            consequence: 1,
                            keepData: true,
                        },
                        {
                            id: 3,
                            question: "Fill in a password:",
                            choices: [],
                            inputType: 2,
                            nextChoice: [4],
                            consequence: 2,
                            keepData: true,
                            resetDataAfterConsequence: true,
                        },
                        {
                            id: 4,
                            question: "Fill in your email:",
                            choices: [],
                            inputType: 2,
                            nextChoice: [5],
                            keepData: true,
                        },
                        {
                            id: 5,
                            question: "Fill in your password:",
                            choices: [],
                            inputType: 2,
                            nextChoice: [],
                            consequence: 3,
                            keepData: true,
                            resetDataAfterConsequence: true,
                        },
                    ],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                },
                {
                    id: 2,
                    name: 'RatonTutorialFight',
                    type: 'animal',
                    animalId: 1,
                    messages: ['brr...'],
                    instaLock: true,
                    skippable: false,
                    thisLocks: [],
                },
            ],
        },
    ];
}